Lab 15/app/cookies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length

class ChangePasswordForm(FlaskForm):
    old_password = PasswordField(label='Old password', validators=[DataRequired("Це поле обов'язкове"),
            Length(min=4, max=10, message="Повинно бути від 4 до 10 символів")])
    new_password = PasswordField(label='New password', validators=[DataRequired("Це поле обов'язкове"),
            Length(min=4, max=10, message="Повинно бути від 4 до 10 символів")])
    submit = SubmitField(label="Зберегти")

Lab 15/app/cookies/__init__.py
from flask import Blueprint

cookies_bp = Blueprint('cookies', __name__, template_folder='templates')

from . import views

Lab 15/app/cookies/views.py
from flask import render_template, request, make_response, redirect, url_for, flash, session
from flask_login import login_required, current_user
from datetime import datetime
from ..extensions import db
from . import cookies_bp
from .forms import ChangePasswordForm

user_session = {}
@cookies_bp.route('/info', methods=['GET', 'POST'])
@login_required
def info():
    form = ChangePasswordForm()

    if current_user.is_authenticated:
        email = current_user.email

        cookies = []
        for key, value in request.cookies.items():
            expiration = request.cookies[key]
            creation_time = session.get(f'cookie_creation_{key}')
            cookies.append({
                'key': key,
                'value': value,
                'expiration': expiration,
                'creation_time': creation_time,
            })

        if request.method == 'POST':
            if 'cookie_key' in request.form and 'cookie_value' in request.form and 'cookie_expiration' in request.form:
                cookie_key = request.form['cookie_key']
                cookie_value = request.form['cookie_value']
                cookie_expiration = int(request.form['cookie_expiration'])

                response = make_response(redirect(url_for('cookies.info')))
                response.set_cookie(cookie_key, cookie_value, max_age=cookie_expiration)
                session[f'cookie_creation_{cookie_key}'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

                flash(f"Cookie '{cookie_key}' added successfully.", 'success')

            if 'delete_cookie_key' in request.form:
                delete_cookie_key = request.form['delete_cookie_key']

                if delete_cookie_key in request.cookies:
                    response = make_response(redirect(url_for('cookies.info')))
                    response.delete_cookie(delete_cookie_key)
                    session.pop(f'cookie_creation_{delete_cookie_key}', None)
                    flash(f"Cookie '{delete_cookie_key}' deleted successfully.", 'success')

            if 'delete_all_cookies' in request.form:
                response = make_response(redirect(url_for('cookies.info')))
                for key in request.cookies:
                    response.delete_cookie(key)
                    session.pop(f'cookie_creation_{key}', None)
                flash("All cookies deleted successfully.", 'success')

            return response

        return render_template('cookies/info.html', email=email, cookies=cookies, form=form)

    else:
        flash("You are not logged in. Please log in to access this page.", "error")
        return redirect(url_for('profile.login'))

@cookies_bp.route('/change_password', methods=['POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        user = current_user

        if user and user.checkPassword(form.old_password.data):
            try:
                # Update the password
                user.set_password(form.new_password.data)
                db.session.commit()
                flash("Password changed", category="success")
            except Exception as e:
                db.session.rollback()
                flash(f"Error: {e}", category="danger")
        else:
            flash("Invalid password", category="danger")
    else:
        flash("Form validation failed", category="danger")

    return redirect(url_for('profile.account'))

@cookies_bp.route('/add_cookie', methods=['POST'])
def add_cookie():
    if 'username' in user_session:
        if request.method == 'POST':
            cookie_key = request.form.get('cookie_key')
            cookie_value = request.form.get('cookie_value')
            cookie_expiration = int(request.form.get('cookie_expiration'))

            response = make_response(redirect(url_for('info')))
            response.set_cookie(cookie_key, cookie_value, max_age=cookie_expiration)
            session[f'cookie_creation_{cookie_key}'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

            flash(f"Cookie '{cookie_key}' added successfully.", 'success')

            return response
        else:
            return redirect(url_for('info'))
    else:
        return redirect(url_for('profile.login'))

@cookies_bp.route('/delete_cookie', methods=['POST'])
def delete_cookie():
    if 'username' in user_session:
        if request.method == 'POST':
            if 'delete_cookie_key' in request.form:
                delete_cookie_key = request.form['delete_cookie_key']

                if delete_cookie_key in request.cookies:
                    response = make_response(redirect(url_for('info')))
                    response.delete_cookie(delete_cookie_key)
                    session.pop(f'cookie_creation_{delete_cookie_key}', None)
                    flash(f"Cookie '{delete_cookie_key}' deleted successfully.", 'success')

                    return response

        return redirect(url_for('info'))
    else:
        return redirect(url_for('profile.login'))

@cookies_bp.route('/delete_all_cookies', methods=['POST'])
def delete_all_cookies():
    if 'username' in user_session:
        if request.method == 'POST':
            response = make_response(redirect(url_for('info')))
            for key in request.cookies:
                response.delete_cookie(key)
                session.pop(f'cookie_creation_{key}', None)
            flash("All cookies deleted successfully.", 'success')

            return response
        return redirect(url_for('info'))
    else:
        return redirect(url_for('profile.login'))

Lab 15/app/cookies/templates/cookies/info.html
{% extends 'base.html' %}
{% from "render_field.html" import render_field %}
{% block title %}INFO{% endblock %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/Info.css') }}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">

    <div class="container text-center">
      <div class="row g-0">
        <div class="col">
          <div class="p-3">
            <h1>INFO page</h1>
            {% if email %}
                <p>Welcome, {{ email }}!</p>
                <form method="POST" action="{{ url_for('profile.logout') }}">
                    <button type="submit" class="btn btn-danger">Logout</button>
                </form>
                <form method="POST" action="{{ url_for('cookies.add_cookie') }}">
                    <h2>Add a Cookie</h2>
                    <div class="form-group">
                        <label for="cookie_key">Key:</label>
                        <input type="text" name="cookie_key" class="form-control" id="cookie_key" required>
                    </div>
                    <div class="form-group">
                        <label for="cookie_value">Value:</label>
                        <input type="text" name="cookie_value" class="form-control" id="cookie_value" required>
                    </div>
                    <div class="form-group">
                        <label for="cookie_expiration">Expiration (in seconds):</label>
                        <input type="number" name="cookie_expiration" class="form-control" id="cookie_expiration" required>
                    </div>
                    <button type="submit" class="btn btn-success">Add Cookie</button>
                </form>

                <form method="POST" action="{{ url_for('cookies.delete_cookie') }}">
                    <h2>Delete a Cookie</h2>
                    <div class="form-group">
                        <label for="delete_cookie_key">Key:</label>
                        <input type="text" name="delete_cookie_key" class="form-control" id="delete_cookie_key" required>
                    </div>
                    <button type="submit" class="btn btn-danger">Delete Cookie</button>
                </form>

                <br>

                <form method="POST" action="{{ url_for('cookies.delete_all_cookies') }}">

                    <button type="submit" class="btn btn-danger">Delete All Cookies</button>
                </form>


                <br><h2>Saved Cookies</h2>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>Key</th>
                      <th>Value</th>
                      <th>Expiration</th>
                      <th>Creation Time</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for cookie in cookies %}
                    <tr>
                      <td>{{ cookie.key }}</td>
                      <td>{{ cookie.value[:50] }}</td>
                      <td>{{ cookie.expiration[:50] }}</td>
                      <td>{{ cookie.creation_time }}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
            {% else %}
                <p>Please log in to access this page.</p>
            {% endif %}
          <br><br><hr>
                <h2>Change Password</h2>
                <form method="POST" action="{{ url_for('cookies.change_password') }}">
                    {{ form.csrf_token }}
                  <div class="form-group">
                    {{ render_field(form.old_password, class="form-control") }}
                  </div>
                  <div class="form-group">
                    {{ render_field(form.new_password, class="form-control") }}
                  </div>
                  {{ render_field(form.submit, class="btn btn-success") }}
                </form>
           </div>
        </div>
      </div>
    </div>
{% endblock %}