Lab 13/app/profile/views.py
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.utils import secure_filename
from . import profile_bp
from .forms import LoginForm, RegistrationForm, ChangePasswordForm, UpdateAccountForm
from .models import User
from app import db
import os
from datetime import datetime
from flask import Blueprint, render_template

resume_bp = Blueprint('resume', __name__, template_folder='templates')

@resume_bp.route('/base')
def base():
    return render_template('resume/base.html')

@resume_bp.route('/index')
def index():
    # Your index route logic here
    return render_template('resume/index.html')

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

@profile_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('cookies.info'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.verify_password(form.password.data):
            login_user(user, remember=form.remember.data)
            flash("Вхід успішний", category="success")
            return redirect(url_for("cookies.info"))

        flash("Invalid email or password", category="danger")
        return redirect(url_for("profile.login"))

    return render_template('profile/login.html', form=form)

@profile_bp.route('/registration', methods=['GET', 'POST'])
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('cookies.info'))
    
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, password=form.password.data)
        try:
            db.session.add(new_user)
            db.session.commit()
            flash(f"Обліковий запис створено для {form.username.data}!", "success")
            return redirect(url_for("profile.login"))
        except:
            db.session.rollback()
            flash("ПОМИЛКА, спробуйте використати інші дані", category="danger")
            return redirect(url_for("profile.registration"))

    return render_template("profile/register.html", form=form)

@profile_bp.route('/logout', methods=['GET', 'POST'])
def logout():
    if request.method == 'POST' or request.method == 'GET':
        logout_user()
        flash("You've been logged out", category="success")
        return redirect(url_for("profile.login"))

@profile_bp.route('/change_password', methods=['POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        user = current_user

        if user and user.checkPassword(form.old_password.data):
            try:
                # Update the password
                user.set_password(form.new_password.data)
                db.session.commit()
                flash("Password changed", category="success")
            except Exception as e:
                db.session.rollback()
                flash(f"Error: {e}", category="danger")
        else:
            flash("Invalid password", category="danger")
    else:
        flash("Form validation failed", category="danger")

    return redirect(url_for('profile.account'))

@profile_bp.route('/users')
def users():
    return render_template('profile/users.html', users=User.query.all())

# pic path #
UPLOAD_FOLDER = 'static/imgs/'
current_app.config['upload_folder'] = UPLOAD_FOLDER

if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)
# end #

@profile_bp.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    update_account_form = UpdateAccountForm(obj=current_user)
    change_password_form = ChangePasswordForm()

    if update_account_form.validate_on_submit():
        current_user.username = update_account_form.username.data
        current_user.email = update_account_form.email.data
        current_user.about_me = update_account_form.about_me.data

        if 'image' in request.files:
            file = request.files['image']
            if file.filename != '':
                filename = secure_filename(file.filename)
                file_path = os.path.join(UPLOAD_FOLDER, filename)
                current_user.image_file = filename

                # Move the file to the UPLOAD_FOLDER
                destination = os.path.join(current_app.root_path, UPLOAD_FOLDER, filename)
                if not os.path.exists(os.path.join(current_app.root_path, UPLOAD_FOLDER)):
                    os.makedirs(os.path.join(current_app.root_path, UPLOAD_FOLDER))
                file.save(destination)

        db.session.commit()
        flash('Account updated successfully!', 'success')
        return redirect(url_for('profile.account'))

    if change_password_form.validate_on_submit():
        if current_user.check_password(change_password_form.old_password.data):
            try:
                current_user.set_password(change_password_form.new_password.data)
                db.session.commit()
                flash('Password changed successfully!', 'success')
                return redirect(url_for('profile.account'))
            except Exception as e:
                db.session.rollback()
                flash(f"Error changing password: {e}", 'danger')
        else:
            flash('Current password is incorrect', 'danger')

    return render_template('profile/account.html', update_account_form=update_account_form, change_password_form=change_password_form, is_authenticated=True, os=os)

@profile_bp.before_request
def update_last_seen():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

Lab 13/app/profile/templates/profile/account.html
<a href="{{ url_for('resume.index') }}" class="btn btn-primary">Go to Base</a>

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
<style>
  body {
    font-family: sans-serif;
    background-color: #f0f0f0;
    text-align: center;
    margin: 0;
    padding: 0;
  }

  .container {
    margin: 0 auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 10px;
    box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
    margin-top: 50px;
  }

  h1 {
    color: #333;
  }

  .card {
    margin-bottom: 20px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }

  .card-body {
    padding: 20px;
  }

  .card-title {
    font-size: 24px;
  }

  .card-subtitle {
    color: #666;
  }

  .card-text {
    margin-top: 10px;
    color: #555;
  }

  @keyframes moveContent {
    from {
      transform: translateX(-100%);
    }
    to {
      transform: translateX(0);
    }
  }

  .btn {
    background-color: #007bff;
    color: #fff;
    padding: 12px 24px;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .btn:hover {
    background-color: #0056b3;
  }

  .form-header {
    background-color: #007bff;
    color: #fff;
    padding: 10px;
    text-align: center;
    border-radius: 5px 5px 0 0;
  }

  .success-message {
    color: #5bc0de;
    font-size: 14px;
  }

  .error-message {
    color: #d9534f;
    font-size: 14px;
  }

  table {
    width: 100%;
    margin-top: 20px;
    border-collapse: collapse;
  }

  th, td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
    white-space: nowrap; 
    overflow: hidden;
    text-overflow: ellipsis;
  }

  th {
    background-color: #f2f2f2;
  }

  .profile img {
    display: block;
    margin: 0 auto;
    border: 4px solid #fff;
    border-radius: 50%;
    object-fit: cover;
    width: 100px; 
    height: 100px; 
  }

  .profile h1 {
    font-size: 24px;
    margin-bottom: 10px;
  }

  .profile p {
    margin-bottom: 0;
  }

  .update-account-form {
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
  }

  .update-account-form h2 {
    font-size: 20px;
    margin-bottom: 20px;
  }

  .update-account-form .form-control {
    margin-bottom: 15px;
  }

  .about-me-label {
    margin-bottom: 5px;
  }

  .last-seen {
    margin-bottom: 20px;
  }

  .change-password-form {
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
    margin-top: 20px;
  }

  .change-password-form h2 {
    font-size: 20px;
    margin-bottom: 20px;
  }

  .change-password-form .form-group {
    margin-bottom: 15px;
  }

  @media (max-width: 768px) {
    .col-lg-6 {
      margin-bottom: 20px;
    }
    .profile img {
      width: 80px;
      height: 80px;
    }
  }
</style>

{% from "render_field.html" import render_field %}
{% block title %}Update Account{% endblock %}
{% block content %}
    <div class="container text-center">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <div class="p-3">
                    <img src="{{ url_for('static', filename='imgs/' + current_user.image_file) }}" alt="Profile Photo" class="mb-3 rounded-circle" style="width: 50%; height: 50%; object-fit: cover;">
                    <h1>{{ current_user.username }}</h1>
                    <p>Email: {{ current_user.email }}</p>
                </div>
                <div class="p-3">
                    <h2>Update Account Information</h2>
                    <form method="POST" enctype="multipart/form-data" class="update-form">
                        {{ update_account_form.hidden_tag() }}
                        <div class="mb-3">
                            {{ render_field(update_account_form.username, 'Enter Username', class="form-control") }}
                        </div>
                        <div class="mb-3">
                            {{ render_field(update_account_form.email, 'Enter Email', class="form-control") }}
                        </div>
                        <div class="mb-3">
                            <p class="about-me-label">About me</p>
                            {{ render_field(update_account_form.about_me, 'About me', class="form-control") }}
                        </div>
                        <div class="mb-3">
                            {{ render_field(update_account_form.image, 'Upload Image', class="form-control") }}
                        </div>
                        <div class="p-3">
                            <p class="last-seen">Last Seen: {{ current_user.last_seen }}</p>
                        </div>
                        <div>
                            {{ render_field(update_account_form.submit, 'Update', class="btn btn-primary") }}
                        </div>
                    </form>
                    <br><br><hr>
                    <h2>Change Password</h2>
                    <form method="POST" action="{{ url_for('profile.change_password') }}">
                        {{ change_password_form.csrf_token }}
                        <div class="form-group">
                            {{ render_field(change_password_form.old_password, 'Current Password', class="form-control") }}
                        </div>
                        <div class="form-group">
                            {{ render_field(change_password_form.new_password, 'New Password', class="form-control") }}
                        </div>
                        {{ render_field(change_password_form.submit, 'Change Password', class="btn btn-success") }}
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Lab 13/app/profile/templates/profile/login.html
<a href="{{ url_for('resume.index') }}" class="btn btn-primary">Go to Base</a>

  <br>  <br>  
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
  <br>  <br> 
{% from "render_field.html" import render_field %}
{% block title %}Login{% endblock %}
{% block content %}
    <div class="container text-center">
      <div class="row g-0">
        <div class="col">
          <div class="p-3">
            <form method="POST" novalidate>
                {{ form.csrf_token }}
              <fieldset>
                <div class="form-group">
                    {{ render_field(form.email, class="form-control") }}
                </div>
                <div class="form-group">
                    {{ render_field(form.password, class="form-control") }}
                </div>
                  <div class="form-group">
                    {{ render_field(form.remember, class="form-check-input") }}
                  </div>
                  {{ render_field(form.submit, class="btn btn-primary") }}
              </fieldset>
            </form>
          </div>
            {% if error_message %}
                <div class="alert alert-danger mt-3" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
        </div>
      </div>
    </div>
{% endblock %}

Lab 13/app/profile/templates/profile/register.html
{% include 'messages.html' %} 
<a href="{{ url_for('resume.index') }}" class="btn btn-primary">Go to Base</a>

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
  <br> <br>
{% from "render_field.html" import render_field %}
{% block title %}Registration{% endblock %}
{% block content %}
    <div class="container text-center">
      <div class="row g-0">
        <div class="col">
          <div class="p-3">
            <form method="POST" novalidate>
                {{ form.csrf_token }}
              <fieldset>
                <div class="form-group">
                    {{ render_field(form.username, class="form-control") }}
                </div>
                <div class="form-group">
                    {{ render_field(form.email, class="form-control") }}
                </div>
                <div class="form-group">
                    {{ render_field(form.password, class="form-control") }}
                </div>
                <div class="form-group">
                    {{ render_field(form.confirm_password, class="form-control") }}
                </div>
                  {{ render_field(form.submit, class="btn btn-primary") }}
              </fieldset>
            </form>
          </div>
            {% if error_message %}
                <div class="alert alert-danger mt-3" role="alert">
                    {{ error_message }}
                </div>
            {% endif %}
        </div>
      </div>
    </div>
{% endblock %}

Lab 13/app/profile/templates/profile/users.html
<a href="{{ url_for('resume.index') }}" class="btn btn-primary">Go to Base</a>

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
  <br> <br> <br>
{% block title %}Users{% endblock %}
{% block content %}
    <div class="container text-center">
        <h1 class="mt-4">Number of users: {{ users|length }}</h1>
        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                {% for user in users %}
                    <div class="card mb-3">
                        <div class="card-body">
                            <h5 class="card-title">{{ user.username }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ user.email }}</h6>
                            <p class="card-text">ID: {{ user.id }}</p>
                        </div>
                    </div>
                {% else %}
                    <div class="alert alert-warning" role="alert">
                        No users found.
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}