Lab 15/app/profile/views.py
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_login import login_user, logout_user, current_user, login_required
from werkzeug.utils import secure_filename
from . import profile_bp
from .forms import LoginForm, RegistrationForm, ChangePasswordForm, UpdateAccountForm
from .models import User
from app import db
import os
from datetime import datetime
from flask import Blueprint

profile_bp = Blueprint('profile', __name__, template_folder='templates')

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

@profile_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('cookies.info'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and user.verify_password(form.password.data):
            login_user(user, remember=form.remember.data)
            flash("Вхід успішний", category="success")
            return redirect(url_for("cookies.info"))

        flash("Invalid email or password", category="danger")
        return redirect(url_for("profile.login"))

    return render_template('profile/login.html', form=form)

@profile_bp.route('/registration', methods=['GET', 'POST'])
def registration():
    if current_user.is_authenticated:
        return redirect(url_for('cookies.info'))

    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, password=form.password.data)
        try:
            db.session.add(new_user)
            db.session.commit()
            flash(f"Обліковий запис створено для {form.username.data}!", "success")
            return redirect(url_for("profile.login"))
        except:
            db.session.rollback()
            flash("ПОМИЛКА, спробуйте використати інші дані", category="danger")
            return redirect(url_for("profile.registration"))

    return render_template("profile/register.html", form=form)

@profile_bp.route('/logout', methods=['GET', 'POST'])
def logout():
    if request.method == 'POST' or request.method == 'GET':
        logout_user()
        flash("You've been logged out", category="success")
        return redirect(url_for("profile.login"))

@profile_bp.route('/change_password', methods=['POST'])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        user = current_user

        if user and user.checkPassword(form.old_password.data):
            try:
                # Update the password
                user.set_password(form.new_password.data)
                db.session.commit()
                flash("Password changed", category="success")
            except Exception as e:
                db.session.rollback()
                flash(f"Error: {e}", category="danger")
        else:
            flash("Invalid password", category="danger")
    else:
        flash("Form validation failed", category="danger")

    return redirect(url_for('profile.account'))

@profile_bp.route('/users')
def users():
    return render_template('profile/users.html', users=User.query.all())

@profile_bp.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    update_account_form = UpdateAccountForm(obj=current_user)
    change_password_form = ChangePasswordForm()

    if update_account_form.validate_on_submit():
        current_user.username = update_account_form.username.data
        current_user.email = update_account_form.email.data
        current_user.about_me = update_account_form.about_me.data

        if 'image' in request.files:
            file = request.files['image']
            if file.filename != '':
                filename = secure_filename(file.filename)
                file_path = os.path.join('static/imgs/', filename)
                current_user.image_file = filename

                # Move the file to the UPLOAD_FOLDER
                destination = os.path.join(current_app.root_path, 'static/imgs/', filename)
                if not os.path.exists(os.path.join(current_app.root_path, 'static/imgs/')):
                    os.makedirs(os.path.join(current_app.root_path, 'static/imgs/'))
                file.save(destination)

        db.session.commit()
        flash('Account updated successfully!', 'success')
        return redirect(url_for('profile.account'))

    if change_password_form.validate_on_submit():
        if current_user.check_password(change_password_form.old_password.data):
            try:
                current_user.set_password(change_password_form.new_password.data)
                db.session.commit()
                flash('Password changed successfully!', 'success')
                return redirect(url_for('profile.account'))
            except Exception as e:
                db.session.rollback()
                flash(f"Error changing password: {e}", 'danger')
        else:
            flash('Current password is incorrect', 'danger')

    return render_template('profile/account.html', update_account_form=update_account_form, change_password_form=change_password_form)

@profile_bp.before_request
def update_last_seen():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()

Lab 15/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--fonts-->
    <link rel='stylesheet'
          href='https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i|Source+Code+Pro:400,500,600,700'
          type='text/css' media='screen'/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:900" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/base.css') }}">
    <title>{% block title %}Main{% endblock %}</title>
</head>
<body>
    {% include 'nav.html' %}
                <div class="margins">
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                    <li class="alert alert-success">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endwith %}

                    {% block content %}
                        <!-- Content from other pages -->
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>

</body>
</html>

Lab 15/app/templates/common.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ common.first_name }} {{ common.last_name }}</title>
</head>
<body>
    
</body>
</html>

Lab 15/app/templates/footer.html
    <div class="alert alert-dismissible alert-secondary">
        <div class="container overflow-hidden text-center">
          <div class="row gx-5">
            <div class="col">
             <div class="p-3">{{ u_agent }}</div>
            </div>
            <div class="col">
              <div class="p-3">{{ OS }}</div>
            </div>
              <div class="col">
              <div class="p-3">{{ time }}</div>
            </div>
          </div>
        </div>
    </div>

Lab 15/app/templates/messages.html
<link rel='stylesheet'
href='https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i|Source+Code+Pro:400,500,600,700'
type='text/css' media='screen'/>
<link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto:900" rel="stylesheet">
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='css/flash.css') }}">

<ul class="messages">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <li class="alert alert-{{ message.category }} animate-in">{{ message }}</li>
            {% endfor %}
        {% endif %}
    {% endwith %}
</ul>

Lab 15/app/templates/nav.html
{% set menu = {
  "Home": url_for('resume.index'),
  "Biography": url_for('resume.biography'),
  "Skills": url_for('resume.skills'),
  "Projects": url_for('resume.projects'),
  "Feedback": url_for('feedback.feedback'),
  "ToDo": url_for('todo.todo'),
  "Users": url_for('profile.users'),
  "Info": url_for('cookies.info'),
  "Posts": url_for('posts.posts_page')
} %}

<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/base.css') }}">
<link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/page.css') }}">

<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Vitalii
      Shmatolokha
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
          {% for name, url in menu.items() %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url }}">{{ name }}</a>
            </li>
          {% endfor %}
      </ul>
      {% if current_user.is_authenticated %}
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('profile.account')}}">Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('profile.logout')}}">Logout</a>
          </li>
        </ul>
      {% else %}
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('profile.registration')}}">Registration</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('profile.login')}}">Login</a>
          </li>
        </ul>
      {% endif %}
    </div>
  </div>
</nav>

Lab 15/app/templates/render_field.html
{% macro render_field(field, placeholderValue) %}

  <div class="form-group">
    {% if field.type in ["StringField", "PasswordField"] %}
        {{ field.label(class="form-label mt-3") }}
        {{ field(class='form-control mt-2', placeholder=placeholderValue, **kwargs) }}
    {% elif field.type == "BooleanField" %}
        {{ field(class='form-check-input mt-2', **kwargs) }}
        {{ field.label(class='form-check-label mt-2') }}
    {% else %}
        {{ field(**kwargs)| safe }}
    {% endif %}

    {% if field.errors %}
      <ul class="errors">
        {% for error in field.errors %}
          <li class="text-danger mt-1">{{ error }}</li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>

{% endmacro %}